#spring:
#  profiles:
#    active: dev
#  application:
#    name: friend-backend
#  # DataSource Config
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://58.87.96.17:3306/friend?serverTimezone=Asia/Shanghai
#    username: yxs666
#    password: yinjie.1218
#  # session 失效时间（分钟）
#  session:
#    timeout: 86400
#    store-type: redis
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
#  #redis配置
#  redis:
#    port: 6379
#    host: 58.87.96.17
#    password: yinjie.1218
#    database: 1
#server:
#  port: 8088
#  servlet:
#    context-path: /api
#    session:
#      cookie:
#        domain: 58.87.96.17
##        same-site: none
##        secure: true
##        domain: 127.0.0.1
##        same-site: none
##        secure: true
#mybatis:
#  config-location: classpath:mybatis/config.xml
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

spring:
  profiles:
    active: dev
  application:
    name: friend-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/friend?serverTimezone=Asia/Shanghai
    username: root
    password: root
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  #redis配置
  redis:
    port: 6379
    host: localhost
    database: 1
    password:
server:
  port: 8081
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis:
  config-location: classpath:mybatis/config.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)